[project]
name = "pdf-overview-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-generativeai>=0.8.3",
    "instructor>=1.6.4",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "jsonref>=1.1.0",
    "jupyterlab-widgets>=3.0.13",
    "ollama>=0.3.3",
    "python-dotenv>=1.0.1",
    "sqlmodel>=0.0.22",
    "toml>=0.10.2",
]
